# Generated by Django 5.1.2 on 2025-01-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
